use crate::services::{Template, TemplateCategory, TemplateService};
use crate::state::app_state::{AppState, Notification};
use leptos::prelude::*;

#[component]
pub fn SaveTemplateModal(show: RwSignal<bool>, on_close: Callback<()>) -> impl IntoView {
    use crate::builder::hooks::use_escape_key::use_escape_key;

    let app_state = AppState::expect_context();

    use_escape_key(show, move || on_close.run(()));

    let name = RwSignal::new(String::new());
    let description = RwSignal::new(String::new());
    let tags = RwSignal::new(String::new());
    let loading = RwSignal::new(false);

    let save_action = move || {
        let name_val = name.get();
        if name_val.trim().is_empty() {
            app_state
                .ui
                .notify(Notification::error("Template name is required".to_string()));
            return;
        }

        loading.set(true);

        // Capture current canvas state
        let components = app_state.canvas.components.get();

        // Create tags list
        let tag_list: Vec<String> = tags
            .get()
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();

        let template = Template::new(
            "", // ID will be generated by backend
            &name_val,
            &description.get(),
            TemplateCategory::Custom,
            components,
        )
        .with_tags(tag_list.iter().map(|s| s.as_str()).collect());

        leptos::task::spawn_local(async move {
            match TemplateService::save_custom_template(&template).await {
                Ok(_) => {
                    app_state.ui.notify(Notification::success(
                        "Template saved successfully".to_string(),
                    ));
                    name.set(String::new());
                    description.set(String::new());
                    tags.set(String::new());
                    on_close.run(());
                }
                Err(e) => {
                    app_state.ui.notify(Notification::error(format!(
                        "Failed to save template: {}",
                        e.user_message()
                    )));
                }
            }
            loading.set(false);
        });
    };

    let on_keydown = move |ev: leptos::web_sys::KeyboardEvent| {
        if ev.key() == "Enter" {
            save_action();
        }
    };

    view! {
        <Show when=move || show.get()>
            <div
                class="modal-backdrop"
                role="presentation"
                on:click=move |_| on_close.run(())
            >
                <div
                    class="modal-content"
                    role="dialog"
                    aria-modal="true"
                    aria-labelledby="save-template-modal-title"
                    style="max-width: 500px"
                    on:click=move |ev: web_sys::MouseEvent| ev.stop_propagation()
                    on:keydown=on_keydown
                >
                    <div class="modal-header">
                        <h3 id="save-template-modal-title">"Save as Template"</h3>
                        <button
                            class="close-btn"
                            aria-label="Close save template dialog"
                            on:click=move |_| on_close.run(())
                        >
                            "×"
                        </button>
                    </div>

                    <div class="modal-body">
                        <div class="form-group">
                            <label>"Name"</label>
                            <input
                                type="text"
                                class="input-text"
                                prop:value=name
                                on:input=move |ev| name.set(event_target_value(&ev))
                                placeholder="My Awesome Template"
                                autofocus
                            />
                        </div>

                        <div class="form-group">
                            <label>"Description"</label>
                            <textarea
                                class="input-text"
                                prop:value=description
                                on:input=move |ev| description.set(event_target_value(&ev))
                                placeholder="Describe your template..."
                                rows=3
                            />
                        </div>

                        <div class="form-group">
                            <label>"Tags (comma separated)"</label>
                            <input
                                type="text"
                                class="input-text"
                                prop:value=tags
                                on:input=move |ev| tags.set(event_target_value(&ev))
                                placeholder="landing, dark, mobile"
                            />
                        </div>

                        <div class="modal-actions">
                            <button
                                class="btn btn-primary"
                                disabled=move || loading.get()
                                on:click=move |_| save_action()
                            >
                                {move || if loading.get() { "Saving..." } else { "Save Template" }}
                            </button>
                            <button
                                class="btn btn-ghost"
                                on:click=move |_| on_close.run(())
                            >
                                "Cancel"
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </Show>
    }
}
